### ISSUE TITLE
Restructure Docs

### ISSUE THREAD

**Issue by NickNunno** [aionrobotics/docs#2]
Create ``dev_branch`` to begin restructuring work. 

**_Do not merge with master until approved_**

Dev branch Sphinx build link here:
https://docs.aionrobotics.com/en/dev_branch/

**Toc-tree:**

- AIONio - Usage Docs
  - aion_control 
  - aion_simulator 
- Vehicles - Mechanical Usage Docs
  - R1 UGV
  - R6 UGV
  - M6 UGV
  - Q775 UAS
- Autopilot
  - Pixhawk 2.1 Autopilot Module
  - Here & Here + GPS Module
  - Here+ (M8N) RTK GPS
- Companion Computer
  - TX2 Hardware 
  - TX2 Software
  - Xavier Hardware
  - Xavier Software
- Sensors
  - Under Construction

**Comment by jmachuca77** [comment]
This has been merged.
